export { DOMAIN_OWNERSHIP } from './domain';
export {
	DEFAULT_THEME_SETTINGS,
	IPC_CHANNELS,
	isDirectoryListing,
	isString,
	isEditorLanguage,
	isEditorTab,
	isFileOperationResult,
	isFileReadResult,
	isFileWriteResult,
	isFsChangeEvent,
	isStartupState,
	isThemeSettings,
	isWorkspaceModel,
	isWorkspaceOpenRequest,
	isWorkspaceSelection,
	isWorkspaceEditInput,
	isWorkspaceEditResult,
	isDiffInput,
	isDiffResult,
	isModelProviderId,
	isModelInfo,
	isModelProviderState,
	isModelGatewayConfig,
	isChatMessage,
	isChatTabState,
	isChatStreamEvent,
	isSendMessageResult,
	isToolCall
} from './ipc';
export type { IdentitySession, IdentitySessionWarning } from './ipc';
export { isIdentitySession, isIdentitySessionWarning, isModelProviderConfig, isTestConnectionResult } from './ipc';
export { pathBasename, normalizePathStr } from './path';
export type { DomainEntityName, DomainOwnership, ModuleName } from './domain';
export type {
	AgentDeckPreloadApi,
	DiagnosticSeverity,
	DirectoryListing,
	EditorDiagnostic,
	EditorLanguage,
	EditorSplitDirection,
	EditorTab,
	EditorTabInput,
	FileEntry,
	FileEntryKind,
	FileOperationResult,
	FileReadResult,
	FileWriteResult,
	FsChangeEvent,
	FsChangeEventKind,
	RecentWorkspace,
	SearchQuery,
	SearchResult,
	StartupServiceDescriptor,
	StartupState,
	ThemePreference,
	ThemeSettings,
	WorkspaceFolder,
	WorkspaceModel,
	WorkspaceOpenKind,
	WorkspaceOpenRequest,
	WorkspaceParseErrorCode,
	WorkspaceSelection,
	WorkspaceEditInput,
	WorkspaceEditOperation,
	WorkspaceEditResult,
	DiffInput,
	DiffResult,
	ModelProviderId,
	ModelInfo,
	ModelProviderStatus,
	ModelProviderState,
	ModelGatewayConfig,
	ChatRole,
	ChatMessage,
	ToolCall,
	ChatTabState,
	ChatStreamEvent,
	SendMessageResult,
	ModelProviderConfig,
	TestConnectionResult
} from './ipc';